cfa_hub_people:
    resource: "@CFAHubPeopleBundle/Controller/"
    type:     annotation
    prefix:   /hub

cfa_hub_marketing:
    resource: "@CFAHubMarketingBundle/Controller/"
    type:     annotation
    prefix:   /hub/marketing


login:
    path:     /login
    defaults: { _controller: CFAHubSecurityBundle:Security:login }

login_check:
    path: /login_check

logout:
    path:   /logout
